[project]
name = "agedap-medical"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fhir-resources>=8.0.0",
    "flet>=0.27.6",
    "requests>=2.32.3",
]
