datasets:
  - dataset_id: 17
    output_directory: "/tmp/breast_cancer_fhe_files/"
    n_estimators: 10
    max_depth: 5
  - dataset_id: 891
    output_directory: "/tmp/diabetes_fhe_files/"
    n_estimators: 10
    max_depth: 5